### ISSUE TITLE
Ordre id i stedet for kurv id

### ISSUE THREAD

**Issue by Henriktha** [onpayio/thirtybees#22]
Hej, er det muligt at få ordre id med over som reference i stedet for kurv id, da kurv id'et er svært at følge igennem bogføring mv.?

**Comment by ebbesmoeller** [comment]
Hej, det er desværre ikke noget vi har mulighed for. Ordre og dertilhørende ID, bliver først oprettet når en betaling er gennemført.
Det er sådan Thirtybees/Prestashop er skruet sammen.
